# Generated by Django 3.2.5 on 2022-01-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageframes',
            name='attempt_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imageframes',
            name='client_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imageframes',
            name='profile_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imageframes',
            name='test_id',
            field=models.IntegerField(default=0),
        ),
    ]
